In [1]:
import numpy as np
import pandas as pd

In [18]:
data=pd.read_csv('forest_fires.csv')

In [19]:
data.head()

   X  Y month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area
0  7  5   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0
1  7  4   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0
2  7  4   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0
3  8  6   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0
4  8  6   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0

In [20]:
# categorical into numeric
data.columns

Index(['X', 'Y', 'month', 'day', 'FFMC', 'DMC', 'DC', 'ISI', 'temp', 'RH',
       'wind', 'rain', 'area'],
      dtype='object')

In [21]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 517 entries, 0 to 516
Data columns (total 13 columns):
X        517 non-null int64
Y        517 non-null int64
month    517 non-null object
day      517 non-null object
FFMC     517 non-null float64
DMC      517 non-null float64
DC       517 non-null float64
ISI      517 non-null float64
temp     517 non-null float64
RH       517 non-null int64
wind     517 non-null float64
rain     517 non-null float64
area     517 non-null float64
dtypes: float64(8), int64(3), object(2)
memory usage: 52.6+ KB

In [22]:
# month and day are categorical 
data.month.replace(('jan','feb','mar','apr','may','jun','jul','aug','sep','oct','nov','dec'),(1,2,3,4,5,6,7,8,9,10,11,12),inplace=True)
data.day.replace(('mon','tue','wed','thu','fri','sat','sun'),(1,2,3,4,5,6,7), inplace=True)

In [23]:
data

     X  Y  month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain   area
0    7  5      3    5  86.2   26.2   94.3   5.1   8.2  51   6.7   0.0   0.00
1    7  4     10    2  90.6   35.4  669.1   6.7  18.0  33   0.9   0.0   0.00
2    7  4     10    6  90.6   43.7  686.9   6.7  14.6  33   1.3   0.0   0.00
3    8  6      3    5  91.7   33.3   77.5   9.0   8.3  97   4.0   0.2   0.00
4    8  6      3    7  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0   0.00
..  .. ..    ...  ...   ...    ...    ...   ...   ...  ..   ...   ...    ...
512  4  3      8    7  81.6   56.7  665.6   1.9  27.8  32   2.7   0.0   6.44
513  2  4      8    7  81.6   56.7  665.6   1.9  21.9  71   5.8   0.0  54.29
514  7  4      8    7  81.6   56.7  665.6   1.9  21.2  70   6.7   0.0  11.16
515  1  4      8    6  94.4  146.0  614.7  11.3  25.6  42   4.0   0.0   0.00
516  6  3     11    2  79.5    3.0  106.7   1.1  11.8  31   4.5   0.0   0.00

[517 rows x 13 columns]

In [24]:
train=data.copy()

In [25]:
train.corr()

,X,Y,month,day,FFMC,DMC,DC,ISI,temp,RH,wind,rain,area
X,1.000000,0.539548,-0.065003,-0.024922,-0.021039,-0.048384,-0.085916,0.006210,-0.051258,0.085223,0.018798,0.065387,0.063385
Y,0.539548,1.000000,-0.066292,-0.005453,-0.046308,0.007782,-0.101178,-0.024488,-0.024103,0.062221,-0.020341,0.033234,0.044873
month,-0.065003,-0.066292,1.000000,-0.050837,0.291477,0.466645,0.868698,0.186597,0.368842,-0.095280,-0.086368,0.013438,0.056496
day,-0.024922,-0.005453,-0.050837,1.000000,-0.041068,0.062870,0.000105,0.032909,0.052190,0.092151,0.032478,-0.048340,0.023226
FFMC,-0.021039,-0.046308,0.291477,-0.041068,1.000000,0.382619,0.330512,0.531805,0.431532,-0.300995,-0.028485,0.056702,0.040122
DMC,-0.048384,0.007782,0.466645,0.062870,0.382619,1.000000,0.682192,0.305128,0.469594,0.073795,-0.105342,0.074790,0.072994
DC,-0.085916,-0.101178,0.868698,0.000105,0.330512,0.682192,1.000000,0.229154,0.496208,-0.039192,-0.203466,0.035861,0.049383
ISI,0.006210,-0.024488,0.186597,0.032909,0.531805,0.305128,0.229154,1.000000,0.394287,-0.132517,0.106826,0.067668,0.008258
temp,-0.051258,-0.024103,0.368842,0.052190,0.431532,0.469594,0.496208,0.394287,1.000000,-0.527390,-0.227116,0.069491,0.097844
RH,0.085223,0.062221,-0.095280,0.092151,-0.300995,0.073795,-0.039192,-0.132517,-0.527390,1.000000,0.069410,0.099751,-0.075519
wind,0.018798,-0.020341,-0.086368,0.032478,-0.028485,-0.105342,-0.203466,0.106826,-0.227116,0.069410,1.000000,0.061119,0.012317
rain,0.065387,0.033234,0.013438,-0.048340,0.056702,0.074790,0.035861,0.067668,0.069491,0.099751,0.061119,1.000000,-0.007366
area,0.063385,0.044873,0.056496,0.023226,0.040122,0.072994,0.049383,0.008258,0.097844,-0.075519,0.012317,-0.007366,1.000000

In [26]:
#train,test split
from sklearn.model_selection import train_test_split
train_set,test_set=train_test_split(train,test_size=0.2,random_state=42)

In [27]:
train_set.head()

     X  Y  month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain   area
329  4  3      9    6  92.2  102.3  751.5   8.4  23.5  27   4.0   0.0   3.33
173  4  4      9    1  90.9  126.5  686.5   7.0  17.7  39   2.2   0.0   3.07
272  2  5      8    2  92.1  152.6  658.2  14.3  20.2  47   4.0   0.0   3.09
497  3  4      8    2  96.1  181.1  671.2  14.3  32.3  27   2.2   0.0  14.68
182  5  4      2    7  86.8   15.6   48.3   3.9  12.4  53   2.2   0.0   6.38

In [28]:
test_set.head()

     X  Y  month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain  area
304  6  5      5    6  85.1   28.0  113.8   3.5  11.3  94   4.9   0.0  0.00
501  7  5      8    2  96.1  181.1  671.2  14.3  21.6  65   4.9   0.8  0.00
441  8  6      8    1  92.1  207.0  672.6   8.2  25.5  29   1.8   0.0  1.23
153  5  4      9    5  94.3   85.1  692.3  15.9  20.1  47   4.9   0.0  1.46
503  2  4      8    3  94.5  139.4  689.1  20.0  29.2  30   4.9   0.0  1.95

In [31]:
#Extracting featires from dataset
X_values=list(train_set['X'])
y_values=list(train_set['Y'])
loc_values=[]
for index in range(0,len(X_values)):
    temp_values=[]
    temp_values.append(X_values[index])
    temp_values.append(y_values[index])
    loc_values.append(temp_values)

In [32]:
loc_values

[[4, 3],
 [4, 4],
 [2, 5],
 [3, 4],
 [5, 4],
 [3, 4],
 [7, 4],
 [3, 4],
 [2, 4],
 [4, 4],
 [2, 4],
 [6, 5],
 [4, 4],
 [1, 2],
 [2, 5],
 [9, 9],
 [7, 4],
 [6, 5],
 [4, 4],
 [1, 3],
 [5, 6],
 [6, 4],
 [1, 2],
 [2, 5],
 [4, 3],
 [4, 4],
 [6, 5],
 [1, 4],
 [1, 5],
 [7, 4],
 [4, 4],
 [4, 4],
 [2, 4],
 [9, 4],
 [1, 4],
 [5, 4],
 [3, 5],
 [2, 3],
 [6, 3],
 [3, 4],
 [2, 5],
 [4, 5],
 [6, 3],
 [4, 3],
 [4, 3],
 [7, 4],
 [8, 5],
 [2, 2],
 [2, 2],
 [7, 6],
 [8, 6],
 [8, 6],
 [6, 3],
 [6, 5],
 [7, 4],
 [8, 6],
 [6, 5],
 [5, 4],
 [8, 6],
 [3, 4],
 [5, 6],
 [2, 5],
 [5, 5],
 [7, 4],
 [4, 5],
 [8, 6],
 [4, 5],
 [8, 4],
 [2, 2],
 [4, 4],
 [1, 4],
 [8, 8],
 [6, 3],
 [8, 6],
 [3, 6],
 [7, 4],
 [8, 6],
 [8, 6],
 [3, 4],
 [4, 5],
 [7, 4],
 [2, 2],
 [8, 6],
 [3, 4],
 [3, 4],
 [6, 5],
 [1, 4],
 [2, 4],
 [5, 4],
 [2, 5],
 [5, 4],
 [8, 6],
 [7, 4],
 [1, 4],
 [4, 5],
 [2, 4],
 [1, 2],
 [8, 6],
 [2, 2],
 [4, 3],
 [6, 5],
 [8, 6],
 [2, 4],
 [4, 6],
 [4, 5],
 [1, 2],
 [4, 5],
 [1, 3],
 [6, 5],
 [8, 6],
 [3, 4],
 [4, 3],
 [8, 6],
 [1, 2],
 [2, 4],
 [6, 5],
 [8, 6],
 [2, 4],
 [3, 4],
 [5, 4],
 [4, 5],
 [8, 6],
 [5, 4],
 [3, 4],
 [3, 4],
 [6, 5],
 [3, 4],
 [6, 5],
 [7, 4],
 [4, 3],
 [2, 4],
 [3, 4],
 [2, 4],
 [6, 5],
 [4, 6],
 [6, 3],
 [6, 5],
 [1, 4],
 [6, 5],
 [6, 6],
 [9, 4],
 [4, 4],
 [2, 2],
 [6, 4],
 [3, 4],
 [6, 5],
 [6, 5],
 [8, 6],
 [3, 4],
 [7, 4],
 [1, 4],
 [2, 4],
 [6, 5],
 [1, 3],
 [7, 3],
 [6, 5],
 [3, 4],
 [4, 5],
 [5, 4],
 [2, 4],
 [8, 3],
 [4, 4],
 [1, 3],
 [3, 4],
 [9, 9],
 [3, 4],
 [1, 2],
 [7, 5],
 [6, 5],
 [3, 4],
 [6, 5],
 [3, 4],
 [7, 4],
 [7, 4],
 [5, 4],
 [2, 5],
 [1, 4],
 [4, 3],
 [3, 4],
 [4, 5],
 [2, 5],
 [3, 4],
 [7, 4],
 [2, 2],
 [5, 4],
 [6, 5],
 [2, 5],
 [8, 6],
 [1, 3],
 [7, 4],
 [6, 4],
 [8, 6],
 [6, 5],
 [6, 5],
 [8, 6],
 [2, 2],
 [3, 4],
 [3, 4],
 [8, 6],
 [4, 5],
 [5, 4],
 [8, 6],
 [7, 5],
 [7, 4],
 [9, 4],
 [8, 6],
 [9, 4],
 [8, 5],
 [3, 6],
 [4, 5],
 [3, 4],
 [6, 4],
 [3, 5],
 [3, 4],
 [4, 5],
 [7, 4],
 [5, 4],
 [4, 4],
 [3, 5],
 [2, 5],
 [1, 3],
 [4, 5],
 [8, 6],
 [1, 4],
 [4, 6],
 [6, 5],
 [4, 4],
 [4, 3],
 [2, 2],
 [3, 4],
 [1, 2],
 [2, 4],
 [8, 6],
 [4, 5],
 [7, 4],
 [6, 5],
 [6, 3],
 [6, 3],
 [5, 4],
 [8, 6],
 [6, 3],
 [8, 6],
 [3, 4],
 [4, 4],
 [4, 3],
 [6, 3],
 [9, 6],
 [4, 4],
 [7, 4],
 [2, 5],
 [4, 4],
 [7, 4],
 [9, 5],
 [2, 2],
 [6, 3],
 [6, 3],
 [6, 3],
 [8, 6],
 [8, 6],
 [8, 6],
 [1, 4],
 [3, 4],
 [7, 5],
 [1, 3],
 [7, 3],
 [1, 4],
 [8, 6],
 [3, 4],
 [4, 5],
 [4, 4],
 [2, 2],
 [6, 6],
 [6, 3],
 [2, 2],
 [6, 5],
 [1, 5],
 [2, 5],
 [7, 4],
 [2, 2],
 [4, 4],
 [2, 4],
 [6, 5],
 [7, 4],
 [6, 3],
 [8, 6],
 [9, 9],
 [2, 2],
 [3, 5],
 [3, 5],
 [6, 6],
 [8, 6],
 [5, 4],
 [9, 9],
 [2, 2],
 [6, 5],
 [6, 5],
 [2, 4],
 [4, 4],
 [4, 5],
 [7, 4],
 [8, 6],
 [4, 4],
 [4, 4],
 [7, 4],
 [2, 5],
 [6, 3],
 [2, 2],
 [7, 5],
 [7, 4],
 [7, 5],
 [4, 3],
 [8, 5],
 [1, 2],
 [8, 3],
 [3, 6],
 [5, 4],
 [4, 4],
 [6, 5],
 [6, 4],
 [4, 4],
 [1, 3],
 [3, 4],
 [6, 5],
 [2, 4],
 [7, 4],
 [4, 5],
 [4, 3],
 [7, 4],
 [7, 4],
 [3, 4],
 [8, 6],
 [4, 4],
 [2, 5],
 [1, 2],
 [4, 5],
 [6, 3],
 [7, 4],
 [6, 3],
 [2, 4],
 [4, 4],
 [4, 5],
 [8, 6],
 [2, 4],
 [4, 4],
 [4, 3],
 [2, 2],
 [4, 4],
 [4, 4],
 [6, 5],
 [3, 4],
 [1, 2],
 [5, 5],
 [4, 6],
 [6, 5],
 [6, 5],
 [6, 5],
 [3, 5],
 [7, 4],
 [6, 5],
 [5, 4],
 [7, 4],
 [4, 3],
 [4, 3],
 [4, 4],
 [5, 4],
 [1, 4],
 [5, 5],
 [7, 4],
 [7, 4],
 [6, 5],
 [1, 5],
 [2, 5],
 [8, 6],
 [2, 2],
 [4, 3],
 [4, 4],
 [6, 3],
 [8, 6],
 [6, 5],
 [5, 4],
 [6, 5],
 [7, 4],
 [7, 4],
 [4, 4],
 [1, 2],
 [2, 5],
 [2, 4],
 [7, 6],
 [7, 5],
 [4, 4],
 [8, 6],
 [4, 3],
 [2, 4],
 [8, 6],
 [4, 6],
 [9, 9],
 [1, 4],
 [3, 4],
 [4, 5],
 [1, 2],
 [8, 6],
 [3, 3],
 [4, 4],
 [6, 5],
 [3, 4],
 [6, 3],
 [6, 4],
 [6, 4],
 [4, 5],
 [4, 5],
 [2, 2],
 [2, 5],
 [2, 4]]

In [33]:
# counting the instances location in the dataset
def count_points(x_points, y_points, scaling_factor):
    count_array=[]
    for index in range(0,len(x_points)):
        temp_values=[x_points[index],y_points[index]]
        count=0
        for value in loc_values:
            if (temp_values==value):
                count=+1
                count_array.append(count * scaling_factor)
    return count_array

In [35]:
#Encoding the data using the Label Encoder
from sklearn.preprocessing import LabelEncoder

month_encoder = LabelEncoder()
day_encoder = LabelEncoder()

months = train['month']
days = train['day']

month_1hot = month_encoder.fit_transform(months) # label encoding month
day_1hot = day_encoder.fit_transform(days) # label encoding day

In [36]:
# Standardizing the data (Feature Scaling) so that all the features are of the same scale
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
numerical_features=train.drop(['month','day'],axis=1)
scaled_featues=sc.fit_transform(numerical_features)

In [42]:
from sklearn.base import BaseEstimator, TransformerMixin

# defining the methods  for the AttributeSelector
class AttributeSelector(BaseEstimator, TransformerMixin):
    def __init__(self, attribute_names):
        self.attribute_names = attribute_names

    def fit(self, X, y=None):
        return self

    def transform(self, X):
        return X[self.attribute_names].values

In [44]:
from sklearn.preprocessing import MultiLabelBinarizer
# defining the methods  for the CustomBinarizer
class CustomBinarizer(BaseEstimator, TransformerMixin):
    def __init__(self, class_labels):
        self.class_labels = class_labels
    def fit(self, X, y=None,**fit_params):
        return self
    def transform(self, X):
        return MultiLabelBinarizer(classes=self.class_labels).fit_transform(X)

In [45]:
# create seperate pipeline for numeric and categorical
from sklearn.pipeline import Pipeline

numerical_attributes=['X', 'Y', 'FFMC', 'DMC', 'DC', 'ISI', 'temp', 'RH', 'wind', 'rain']
categorical_attributes = ['month', 'day']
categorical_classes = np.concatenate((train['month'].unique(), train['day'].unique()), axis=0)
# creating the separate numerical and categorical pipelines
numerical_pipeline = Pipeline([
    ('selector', AttributeSelector(numerical_attributes)),
    ('standardize', StandardScaler()),
])
categorical_pipeline = Pipeline([
    ('selector', AttributeSelector(categorical_attributes)),
    ('encode', CustomBinarizer(categorical_classes)),
])

In [46]:
#  Separating the features and labels into X and Y
X = train.iloc[:,[0,1,2,3,4,5,6,7,8,9,10,11]].values
Y = train.iloc[:, 11].values

In [47]:
X

array([[ 7. ,  5. ,  3. , ..., 51. ,  6.7,  0. ],
       [ 7. ,  4. , 10. , ..., 33. ,  0.9,  0. ],
       [ 7. ,  4. , 10. , ..., 33. ,  1.3,  0. ],
       ...,
       [ 7. ,  4. ,  8. , ..., 70. ,  6.7,  0. ],
       [ 1. ,  4. ,  8. , ..., 42. ,  4. ,  0. ],
       [ 6. ,  3. , 11. , ..., 31. ,  4.5,  0. ]])

In [ ]:
# we can use customized ml Algos